apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitsourceanalyses.devconsole.openshift.io
spec:
  group: devconsole.openshift.io
  names:
    kind: GitSourceAnalysis
    listKind: GitSourceAnalysisList
    plural: gitsourceanalyses
    singular: gitsourceanalysis
  scope: Namespaced
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            gitSourceRef:
              minimum: 1
              properties:
                name:
                  type: string
                  minimum: 1
        status:
          properties:
            state:
              type: boolean
              minimum: 1
            buildEnvStatistics:
              properties:
                sortedLanguages:
                  type: array
                  items:
                    type: string
                detectedBuildTypes:
                  type: array
                  items:
                    properties:
                      language:
                        type: string
                        minimum: 1
                      name:
                        type: string
                        minimum: 1
                      detectedFiles:
                        type: array
                        items:
                          type: string
            error:
              type: string
  version: v1alpha1

